apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nutrition-postgres-pvc
  namespace: nutrition-dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 5Gi
